### PR TITLE
Show usernames of approvers and vetoers

### LINKED ISSUE #402: Show approvers in PR status
This is somewhat a precondition to make #372 useful, we must log who approved. Also it makes for a nicer UX to explicitly see who counted as approver.

### PR DESCRIPTION
**Pull request by prayerslayer**
Fixes #402 

* New text in success case: `Approvals: <list of approvers>`
* New text in case of veto: `Vetoes: <list of vetoers>`

### CODE REVIEW

**Comment by hjacobs** [comment]
Why so inconsistent? Either have "Approved by ... " / "Vetoed by ..." or "Approvers: ..." / "Vetos: ...".

I would prefer "Approved by ..." / "Vetoed by ...".

**Comment by prayerslayer** [comment]
At this point we need to save characters as the message gets clipped after ~70, so I prefer not to have "by". I don't like Approvers+Vetos because approvers are people and vetos are not. How about "Approvals: <list>" and "Vetos: <list>"?

**Comment by alexkops** [comment]
The plural of "veto" is "vetoes" :neckbeard:

**Comment by prayerslayer** [comment]
Well, actually :neckbeard: :grin: both is okay according to [this dictionary](http://www.dict.cc/?s=vetos).

**Comment by alexkops** [comment]
I summon @LappleApple to cast a Salomonic judgement

**Comment by LappleApple** [comment]
@alexkops @prayerslayer You could go old-school and use "yea's" and "nay's". Or informal: "yups" and "nopes." But "approvals" and "vetoes" is also good...

**Comment by prayerslayer** [comment]
I actually like Yea's and Nay's. Maybe for 2.0, let's go with approvals and veto**e**s.

**Comment by prayerslayer** [comment]
👍

**Comment by ChristianLohmann** [comment]
👍

**Pull request merged**
