### PR TITLE
Test and develop with postgres

### PR DESCRIPTION
**Pull request by prayerslayer**
Using multiple database engines for developing, testing (both sqlite3) and production (postgres) can lead to subtle inconsistencies that aren't caught in unit/integration tests.

One example for this are `BIGINT` columns. With sqlite these are stored as `INTEGER` and returned as `number`. With postgres they are stored as `BIGINT` and [returned](https://github.com/brianc/node-postgres/pull/353) as `string`.

This PR adapts tests for postgres and provides a `docker-compose` file to run both zappr and postgres locally.

### CODE REVIEW

**Comment by neremic** [comment]
:+1:

**Comment by prayerslayer** [comment]
Sorry, still found places where we worked around sqlite/pg differences 😓  But I think that's it.

**Comment by ChristianLohmann** [comment]
👍

**Comment by prayerslayer** [comment]
👍

**Pull request merged**
