### PR TITLE
Support commit patterns anywhere in the multiline message

### LINKED ISSUE #341: Support multiline commit messages
Currently we create a new `RegExp` without any modifiers, which causes a commit message like

~~~
feat(docs): foo foo

#123 awesome
~~~

to fail as the ticket id is not on the first line.

### Needed

- [ ] CommitMessage check uses multiline Regex
- [ ] Tests for it

### PR DESCRIPTION
**Pull request by prayerslayer**
Fixes #341

### CODE REVIEW

**Comment by sebastianpoeplau** [comment]
👍

**Comment by hjacobs** [comment]
:+1:

**Comment by hjacobs** [comment]
@sebastianpoeplau you need to make your membership status "public" for the zalando org in order for Zappr to recognize your approval (:+1:). Search your name on https://github.com/orgs/zalando/people and  change "private" to "public".

**Comment by sebastianpoeplau** [comment]
@hjacobs good point, thanks!

**Comment by prayerslayer** [comment]
@hjacobs i think that was just a zappr glitch :(

**Comment by sebastianpoeplau** [comment]
Hmm, right, my membership is public already...

**Comment by prayerslayer** [comment]
👍

**Pull request merged**
