### PR TITLE
#471 docs: remove lgtm licensing fee

### LINKED ISSUE #471: LGTM will not require a licensing fee
This is a docs issue. LGTM is open sourced under Apache 2.0 so they won't be requiring a licensing fee for enterprise github. See here: https://github.com/lgtmco/lgtm-docs/issues/7 

There should be an update to https://zappr.readthedocs.io/en/latest/competitors/ to remove the line 

> LGTM "will require a modest licensing fee for on-premise enterprise use in the near future". Zappr/Zappr Enterprise is completely free (as in beer and freedom) to use.

### PR DESCRIPTION
**Pull request by prayerslayer**
Fixes #471

### CODE REVIEW

**Comment by prayerslayer** [comment]
👍

**Comment by hjacobs** [comment]
Hmm, why do we remove them? The site is still there..

**Comment by prayerslayer** [comment]
> @hjacobs: Hmm, why do we remove them? The site is still there..

It's still there, but it's not primarily about PR reviews anymore. More like code analysis, which is not our cup of tea 😃

**Comment by hjacobs** [comment]
@prayerslayer but the homepage still gives me the impression that "approvals" are the primary thing.

**Comment by prayerslayer** [comment]
Thanks, apparently I mixed up the TLDs. lgtm.co is our competitor, lgtm.io redirects to lgtm.com which is a completely different thing.

**Comment by prayerslayer** [comment]
👍

**Comment by hjacobs** [comment]
:+1:

**Pull request merged**
