### PR TITLE
application/problem+json

### LINKED ISSUE #330: Add middleware for application/problem+json
In API handlers we should be able to throw a certain error instance that will be picked up by this middleware. It should also handle generic errors. All errors should be converted to satisfy the [application/problem+json RFC](https://tools.ietf.org/html/rfc7807#section-3), so that our frontend can handle errors in a generic way.

### PR DESCRIPTION
**Pull request by prayerslayer**
Fixes #330 

todo:

- [x] Change frontend redux actions to not expect text in error case

### CODE REVIEW

**Comment by prayerslayer** [comment]
@spaudanjo @mfellner plz review!

**Comment by neremic** [comment]
:+1:

**Comment by neremic** [comment]
:+1:

**Comment by prayerslayer** [comment]
👍

**Comment by neremic** [comment]
:+1:

**Comment by prayerslayer** [comment]
👍

**Pull request merged**
