### PR TITLE
Audit log support

### LINKED ISSUE #372: Audit log support
As we write "compliance" on our banners there should be the possibility to create some kind of audit log. A file in the simplest case, but it could also be a remote API.

### PR DESCRIPTION
**Pull request by prayerslayer**
Fixes #372 

* Introduces a new service for audit logging (`AuditService`) which exposes a `log` function. 
* Introduces a generic Zappr audit event
* How the logged audit event looks like and where it goes can be configured with appropriate shippers and transformers
* Provides `Console`, `File` and `ZalandoAuditTrail` shipper
* Provides `Identity` and `ZalandoAuditTrail` transformer
* AuditService filters by organization (we only need to track `zalando*` orgs on Github.com)
* If call to Audit API fails for whatever reason, PR will be blocked **discussion needed**
* Currently supported audit event: Zappr set a new state on the PR

I don't expect this to be mergable, let's discuss the changes 😃 

Still needed: 

- [x] Verify locally that the certificate chain works
- [x] Docs

### CODE REVIEW

**Comment by neremic** [comment]
:+1:

**Comment by prayerslayer** [comment]
:-1:

**Comment by prayerslayer** [comment]
Added possibility to not write audit logs at all.

**Comment by ChristianLohmann** [comment]
👍

**Comment by prayerslayer** [comment]
👍

**Pull request merged**
