### PR TITLE
#522 fix: Fix for edited and deleted by another user outdated comment

### PR DESCRIPTION
**Pull request by vecmezoni**
Fix for https://github.com/zalando/zappr/issues/522

New frozen comment was added to the `frozenComments` without `created_at` check.

### CODE REVIEW

**Comment by vecmezoni** [comment]
@zalando/zappr can anyone review this please?

**Comment by harti2006** [comment]
Thanks for the PR and sorry for the delay. It somehow went under between all the GitHub notifications. Will check in the next days.

**Comment by lotharschulz** [comment]
@harti2006 @vecmezoni and me agreed to have additional tests to cover the [#522 cases](https://github.com/zalando/zappr/issues/522):

- Person B/A approves (status: 1/2 approvals ...)
- Person B changes the comment of Person A to any other comment (status: 2/2 approvals....

@vecmezoni volunteered to work on those tests

**Comment by vecmezoni** [comment]
@zalando/zappr updated my test to cover test case provided in #522. 
Sorry that it took so long.

**Comment by vecmezoni** [comment]
@zalando/zappr ping once again

**Comment by harti2006** [comment]
:+1:

**Comment by lotharschulz** [comment]
travis test include:

```
npm ERR! zappr@0.1.0-alpha.1 test-server: `DEBUG='zappr:test' MORGAN_THRESH=999 NODE_ENV=test BABEL_ENV=test BABEL_DISABLE_CACHE=1 mocha --recursive --compilers js:babel-register test/server/`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the zappr@0.1.0-alpha.1 test-server script 'DEBUG='zappr:test' MORGAN_THRESH=999 NODE_ENV=test BABEL_ENV=test BABEL_DISABLE_CACHE=1 mocha --recursive --compilers js:babel-register test/server/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zappr package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     DEBUG='zappr:test' MORGAN_THRESH=999 NODE_ENV=test BABEL_ENV=test BABEL_DISABLE_CACHE=1 mocha --recursive --compilers js:babel-register test/server/
```

**Comment by vecmezoni** [comment]
@lotharschulz I'll check it today

**Comment by vecmezoni** [comment]
I've rebased my branch and updated stubs according to the latest update here https://github.com/zalando/zappr/commit/62660e23f5204a7aacfbafbb3e43b5cf6326a15f. 

Now tests are passing.

**Comment by lotharschulz** [comment]
👍

**Comment by harti2006** [comment]
:+1:

**Comment by vecmezoni** [comment]
@lotharschulz  @harti2006 
Should we merge it? :)

**Pull request closed without merging**
