### PR TITLE
Upgrade docker base image

### LINKED ISSUE #433: Upgrade docker base image
The old one has fixable MEDIUM CVEs.

### PR DESCRIPTION
**Pull request by prayerslayer**
Fixes #433

### CODE REVIEW

**Comment by mfellner** [comment]
@prayerslayer Please change the commit messages to match the Zappr pattern! 😿

**Comment by prayerslayer** [comment]
But when we squash and merge there will be the pull request number as spec reference in master anyways...

**Comment by prayerslayer** [comment]
Done.

**Comment by ChristianLohmann** [comment]
👍

**Comment by prayerslayer** [comment]
👍

**Pull request merged**
