### PR TITLE
Update base image; remove github action

### PR DESCRIPTION
**Pull request by scherniavsky**
Update the OS image to a compliant version and fix the build and test issues: https://github.bus.zalan.do/machinery/planning/issues/2427

Also removes a github action that has been previously auto-added, but has no actual value:

image

### CODE REVIEW

**Comment by scherniavsky** [comment]
Needs another round of testing before merging.

**Review by Olamyy — APPROVED** [review]

**Comment by scherniavsky** [comment]
The change has been deployed in test (https://github.bus.zalan.do/machinery/zappr-deploy/pull/72) and successfully tested (https://github-testbed.machinery.zalan.do/machinery-demo/onboarding-repo/pull/2). The PR can be merged now.

**Comment by scherniavsky** [comment]
:+1:

**Comment by scherniavsky** [comment]
@Olamyy here we also rely on Zappr, so GHE approvals don't have any effect. Please approve it with the regular thumbsup.

**Comment by scherniavsky** [comment]
:+1:

**Comment by kanistha** [comment]
👍

**Comment by tkrop** [comment]
👍

**Pull request merged**
