### PR TITLE
Adds docker-compose up postgres-test

### PR DESCRIPTION
**Pull request by frometor**
Adds docker-compose up postgres-test to make `./init_db.sh` successful Set up test database.

### CODE REVIEW

**Comment by frometor** [comment]
@lotharschulz Basically what I am trying to do is setting up the zappr application locally following the documentation. The Documentation (https://github.com/zalando/zappr#development) says that I should only spin up `docker-compose up postgres-dev`. When I run the command `./init_db.sh` to set up the one database it is complaining that the postgres-test container is missing. If you approve my PR at least the `./init_db.sh` will run successfully as it provides the second missing docker container. I had a discussion with @fokusferit about this. I think I will stay in touch with him.

**Comment by lotharschulz** [comment]
@fokusferit : LGTM, WDYT about this one?

**Comment by fokusferit** [comment]
Sorry for my quite late response but due to reaching OKR's it's quite stressy 😅 
Let's merge it, we did this on Hacktoberfest together and definitely the docs are outdated or docker-compose changed somehow.

**Comment by fokusferit** [comment]
👍

**Comment by lotharschulz** [comment]
👍

**Pull request merged**
