### PR TITLE
Filter comments by created_at timestamp

### LINKED ISSUE #351: Comments on PR are not processed correctly
Situation on #348 as of now:

* @gagoman and me approve PR
* @gagoman pushes to PR
* Only me approves since then

Expected behavior: Status check is set to 1/2 approvals, PR is blocked

Actual behavior: Status check has 2/2 approvals, PR can be merged

Reason: We fetch comments from the Github API with `since` parameter set to when we last encountered a push on the pull request. Instead of returning comments that were **created** since this timestamp, the API returns comments **created or updated** since. Because they are not filtered, but taken into account as-is, edited comments can count as approvals **when they were edited after the last push happened**.

### PR DESCRIPTION
**Pull request by prayerslayer**
Fixes #351

### CODE REVIEW

**Comment by harti2006** [comment]
There is a test case missing : "Show everything if 'since' is not present"

**Comment by prayerslayer** [comment]
Fair enough :) Wait for it...

**Comment by harti2006** [comment]
👍

**Comment by taojang** [comment]
:+1:

**Pull request merged**
