### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by LappleApple**
added license text; also, please check that the code blocks now run in sequence. I shoved them to the end when I created the README, because they weren't very clear (not sure what the first one does).

### CODE REVIEW

**Comment by mfellner** [comment]
1. I think we should add a headline below "Setup and Running Zappr", e.g. "Development", that distinguishes the user documentation from the technical documentation for contributing developers (starts with the code block of exported environment variables).
2. Adding the license information to the README as well seems a bit redundant. Wouldn't it be enough to just write [MIT License](https://github.com/zalando/zappr/blob/master/LICENSE) and link to the LICENSE file?

**Comment by LappleApple** [comment]
@mfellner As for #2, we copy the license in the readme as a standard practice, see https://github.com/zalando/zalando-howto-open-source. As for #1, works for me.

**Comment by mfellner** [comment]
Ok, I just
* updated the license year to 2016
* formatted the raw readme a little bit
* added a "Development" header and a missing instruction to export shell variables

**Comment by mfellner** [comment]
:+1:

**Pull request merged**
