### PR TITLE
Build single docker image

### LINKED ISSUE #359: Build one Docker image
Is there anything speaking against building only one Docker image instead of two (`opensource` and `enterprise`) and just choosing the variant at application start? The code is the same, as far as I can tell the only differene is the default Zappr configuration.

It would have some benefits:
- Simpler pipelines for building and deploying
- We can distribute ONE Docker image to be used by everyone

### PR DESCRIPTION
**Pull request by prayerslayer**
Fixes #359 
- Load config from single file `config/config.yaml`
- This file is cool for local development
- For production purposes other Docker layers will overwrite it

Don't merge until you're willing to fix the build pipelines! 😉 
### Todo afterwards
- [x] Fix `Dockerfile.external` to work with new `zappr-base` image

### CODE REVIEW

**Comment by gagoman** [comment]
It is better to provide build argument. Default one for opensource and custom one for enterprise

**Comment by prayerslayer** [comment]
> It is better to provide build argument

Would love to see arguments instead of facts 😉 What would be the drawbacks?

**Comment by prayerslayer** [comment]
An alternative, which I prefer by now since #418 introduces a whole lot of configuration that will be different between `opensource` and `enterprise` AND it's just cleaner: Build one "base" Zappr image without configuration, then add the final configuration layer with separate Dockerfiles.

Pro: Super clean, reasonably easy to use for everyone.

Con: Serious maintenance effort in our build pipelines.

**Comment by prayerslayer** [comment]
Updated PR and original comment

**Comment by mfellner** [comment]
Looks good!

@gagoman has a point though. Using a build argument for the configuration file path (however using a default value in the Dockerfile) would be even better. Otherwise users need to derive their own Dockerfile based on ours if they want to override the configuration. What do you think?

**Comment by prayerslayer** [comment]
> Otherwise users need to derive their own Dockerfile based on ours if they want to override the configuration.

I thought this would be a good thing:

* We provide a `zappr` Docker image
* Users who want to run their own Zappr have something like this:

~~~ dockerfile
FROM zappr:latest
COPY my-config.yaml $ZAPPR_CONFIG/config.yaml
~~~

If they want code changes too, they can still use the Dockerfile that's in the repository anyways? Do I miss something?

**Comment by mfellner** [comment]
> Users who want to run their own Zappr have something like this
Yes, that's OK.

If we don't have any use for a flexible configuration during build (because we use the same config.yaml at all times) then we don't need a build variable.

👍

**Comment by mfellner** [comment]
@prayerslayer Please resolve the merge conflicts! 😿

**Comment by prayerslayer** [comment]
I'll fix the conflicts soon.

**Comment by prayerslayer** [comment]
Fixed!

**Comment by LappleApple** [comment]
@mfellner @prayerslayer @spaudanjo Hey guys, this PR is a bit dusty/old. What do you plan to do?

**Comment by prayerslayer** [comment]
Merging, eventually, but it's not urgent or anything.

**Comment by harti2006** [comment]
:+1:

**Comment by prayerslayer** [comment]
👍

**Pull request merged**
