### PR TITLE
Visible config errors

### LINKED ISSUE #295: Log YAML parse errors
Currently zappr sometimes falls back to default configuration for no obvious reason and apparently this is a oftentimes a YAML parse error. We cannot prevent user errors, but this should be logged at the very least. We could also provide the `js-yaml` error message via an `error` commit status instead of silently falling back to default.

### PR DESCRIPTION
**Pull request by prayerslayer**
Fixes #295 

image

### CODE REVIEW

**Comment by prayerslayer** [comment]
Summoning @mfellner @spaudanjo, please review

**Comment by neremic** [comment]
:+1:

**Comment by prayerslayer** [comment]
👍

**Comment by prayerslayer** [comment]
👍

**Comment by neremic** [comment]
:+1:

**Pull request merged**
